main:
  - name: "主页"
    url: /
    weight: 10
  - name: "活动"
    url: /#activities
  - name: "教育 & 实习经历"
    url: /#experience
  - name: "技能 & 业余爱好"
    url: /#s_h
  - name: "获奖经历"
    url: /#awards
    weight: 20
  - name: "项目经历"
    url: /#projects
    weight: 30
